"""Stage 7: reporting.

Two views of the SAME underlying review (this is the manipulation in Claim 1):
  report.md / report_only text      : the final report (PRISMA counts, tables, synthesis)
  report_evidence.html / evidence text : report + supporting passages, quote checks, criterion-level
                                         eligibility decisions, term IDs, flags, revision history,
                                         and a feedback box that produces a CLI command.
"""
from __future__ import annotations

import html
import json

from ..context import Ctx


def prisma(ctx: Ctx) -> dict:
    st = ctx.store
    s = (st.get("search") or {}).get("data", {})
    screens = st.by_type("screen")
    ta_excl = [n for n in screens if n["data"]["stage"] == "title_abstract" and n["data"]["decision"] == "exclude"]
    ft = [n for n in screens if n["data"]["stage"] == "full_text"]
    ft_excl = [n for n in ft if n["data"]["decision"] == "exclude"]
    reasons = {}
    for n in ft_excl:
        for c in n["data"].get("because", []) or ["unspecified"]:
            reasons[c] = reasons.get(c, 0) + 1
    return {"identified": s.get("n_identified"), "duplicates": s.get("n_duplicates"),
            "screened": len(screens), "excluded_title_abstract": len(ta_excl),
            "fulltext_assessed": len(ft), "excluded_fulltext": len(ft_excl),
            "excluded_fulltext_reasons": reasons,
            "awaiting_classification": sum(1 for n in screens if n["data"]["decision"] == "awaiting"),
            "included": len(st.included_ids())}


def review_title(p: dict) -> str:
    import re
    t = p.get("title") or "Systematic review"
    return re.sub(r"\s*[:\-]\s*(a\s+)?systematic review protocol\s*$", ": a systematic review", t, flags=re.I)


def _crit_lookup(ctx):
    p = (ctx.store.get("protocol") or {}).get("data", {})
    return {c["id"]: c["text"] for c in p.get("criteria", [])}


def report_markdown(ctx: Ctx) -> str:
    st = ctx.store
    p = st.get("protocol")["data"]
    pr = prisma(ctx)
    crit = _crit_lookup(ctx)
    fields = [f["name"] for f in ctx.topic["extraction_fields"]]
    L = [f"# {review_title(p)}", "",
         f"**Review question.** {p.get('question')}", "",
         "*Research prototype output. Generated by an AI agent; requires human verification before any use.*", "",
         "## Methods", "",
         "**Eligibility criteria**", ""]
    L += [f"- {c['id']} ({c['type']}, {c.get('stage', 'title_abstract')}): {c['text']}" for c in p.get("criteria", [])]
    s = (st.get("search") or {}).get("data", {})
    L += ["", f"**Search.** PubMed: `{s.get('query', '')}` ({s.get('hits', '?')} hits).", "",
          "## Study selection (PRISMA)", "",
          f"Records identified: {pr['identified']}; duplicates removed: {pr['duplicates']}; "
          f"screened: {pr['screened']}; excluded at title/abstract: {pr['excluded_title_abstract']}; "
          f"full texts assessed: {pr['fulltext_assessed']}; excluded at full text: {pr['excluded_fulltext']}; "
          f"awaiting classification (human decision needed): {pr['awaiting_classification']}; "
          f"**included: {pr['included']}**.", ""]
    ft_ex = [n for n in st.by_type("screen") if n["data"]["stage"] == "full_text" and n["data"]["decision"] == "exclude"]
    if ft_ex:
        L += ["**Studies excluded at full text**", "", "| Study | Title | Reason |", "|---|---|---|"]
        for n in ft_ex:
            rid = n["id"].split(":", 1)[1]
            t = st.get(f"rec:{rid}")["data"].get("title", "")[:90]
            why = "; ".join(f"{c}: {crit.get(c, '')}" for c in n["data"].get("because", []))
            L.append(f"| {rid} | {t} | {why} |")
        L.append("")
    L += ["## Characteristics of included studies", "",
          "| Study | " + " | ".join(fields) + " |", "|" + "---|" * (len(fields) + 1)]
    for rid in st.included_ids():
        n = st.get(f"ext:{rid}")
        if not n or n["status"] != "active":
            continue
        vals = [n["data"]["fields"].get(f, {}).get("value", "NR").replace("|", "/").replace("\n", " ") for f in fields]
        L.append(f"| {rid} | " + " | ".join(vals) + " |")
    L += ["", "## Risk of bias (draft)", ""]
    doms = [d["name"] for d in ctx.topic["rob_domains"]]
    L += ["| Study | " + " | ".join(doms) + " | Overall |", "|" + "---|" * (len(doms) + 2)]
    for rid in st.included_ids():
        n = st.get(f"rob:{rid}")
        if not n or n["status"] != "active":
            continue
        jd = {d.get("domain"): d.get("judgment") for d in n["data"]["domains"]}
        L.append(f"| {rid} | " + " | ".join(str(jd.get(d, "?")) for d in doms) + f" | {n['data']['overall']} |")
    L += ["", "## Synthesis", ""]
    for n in st.by_type("synthesis", active_only=True):
        d = n["data"]
        L.append(f"- **[{d['id']}]** {d['text']} [{', '.join(d['cites'])}]")
    L += ["", "## References (included studies)", ""]
    for rid in st.included_ids():
        r = st.get(f"rec:{rid}")["data"]
        L.append(f"- [{rid}] {r.get('authors', '')}. {r.get('title', '')} {r.get('journal', '')} {r.get('year', '')}. "
                 f"{'PMID ' + r['pmid'] if r.get('pmid') else ''} {'doi:' + r['doi'] if r.get('doi') else ''}")
    return "\n".join(L) + "\n"


def evidence_text(ctx: Ctx, max_chars_per_study: int = 0) -> str:
    """Plain-text evidence-linked bundle (used by the simulated reviewer in Claim 1)."""
    st = ctx.store
    crit = _crit_lookup(ctx)
    L = ["## EVIDENCE-LINKED DETAILS", "", "### Eligibility decisions (criterion level)"]
    for n in st.by_type("screen"):
        rid = n["id"].split(":", 1)[1]
        d = n["data"]
        if d["stage"] == "title_abstract" and d["decision"] == "exclude" and not n["flags"]:
            # keep bundle compact: TA exclusions listed briefly
            L.append(f"[screen:{rid}] {d['decision']} at {d['stage']} because {d.get('because')}")
            continue
        L.append(f"[screen:{rid}] decision={d['decision']} stage={d['stage']} because={d.get('because')}")
        for a in d.get("criteria", []):
            L.append(f"    {a.get('id')} ({crit.get(a.get('id'), '')[:60]}): {a.get('assessment')} | evidence: {_ev_txt(a)}")
    L += ["", "### Extracted data with supporting passages"]
    for rid in st.included_ids():
        n = st.get(f"ext:{rid}")
        if not n:
            continue
        L.append(f"[ext:{rid}] (source: {n['data']['source_kind']})")
        for k, v in n["data"]["fields"].items():
            chk = v.get("check", {}).get("status", "-")
            tm = "; ".join(f"{t['term']}->{t['status']} {t['ids']}" for t in v.get("terms", []))
            L.append(f"    {k}: {v['value']} | evidence[{chk}]: {_ev_txt(v)}" + (f" | terms: {tm}" if tm else ""))
    L += ["", "### Risk-of-bias rationales"]
    for rid in st.included_ids():
        n = st.get(f"rob:{rid}")
        if not n:
            continue
        L.append(f"[rob:{rid}] overall={n['data']['overall']}")
        for d in n["data"]["domains"]:
            L.append(f"    {d.get('domain')}: {d.get('judgment')} | {d.get('rationale', '')} | evidence: {_ev_txt(d)}")
    L += ["", "### Synthesis statements: cited evidence and self-check"]
    for n in st.by_type("synthesis", active_only=True):
        v = n["data"].get("verification") or {}
        L.append(f"[{n['data']['id']}] cites={n['data']['cites']} scope={n['data'].get('scope', '')} "
                 f"self-check={v.get('support', 'n/a')}")
        L.append("    populations of cited studies: " + cited_populations(ctx, n["data"]["cites"]))
    flags = [(n["id"], f) for n in st.nodes.values() for f in n["flags"] if f["status"] == "open"]
    if flags:
        L += ["", "### Open flags"] + [f"[{nid}] {f['text']}" for nid, f in flags]
    return "\n".join(L)


def sources_text(ctx: Ctx, rids: list[str] | None = None, max_chars: int = 6000) -> str:
    st = ctx.store
    rids = rids if rids is not None else st.included_ids()
    out = ["## SOURCE PAPERS"]
    for rid in rids:
        t, kind = st.text_of(rid)
        out.append(f"\n### Source {rid} ({kind})\n{t[:max_chars]}")
    return "\n".join(out)


# --------------------------------------------------------------------------- HTML
_CSS = """
:root{--bg:#fff;--fg:#1d1d1f;--mut:#666;--line:#e3e3e3;--ok:#1a7f37;--warn:#9a6700;--bad:#cf222e;--acc:#0b5cad;--chip:#f3f4f6}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#16171a;--fg:#e8e8ea;--mut:#a0a0a8;--line:#33343a;--chip:#25262b;--acc:#6cb0ff}}
body{background:var(--bg);color:var(--fg);font:15px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;max-width:1100px;margin:0 auto;padding:16px}
table{border-collapse:collapse;width:100%;font-size:13px;display:block;overflow-x:auto}td,th{border:1px solid var(--line);padding:4px 6px;vertical-align:top;text-align:left}
details{margin:2px 0}summary{cursor:pointer}.q{color:var(--mut);font-style:italic}
.b{display:inline-block;padding:0 6px;border-radius:8px;font-size:11px;background:var(--chip)}
.exact,.validated,.supported,.low,.include{color:var(--ok)}.fuzzy,.approximate,.partially_supported,.some_concerns,.uncertain{color:var(--warn)}
.not_found,.unsupported,.high,.exclude{color:var(--bad)}.flag{color:var(--bad);font-size:13px}
textarea{width:100%;min-height:60px;background:var(--bg);color:var(--fg);border:1px solid var(--line)}
code{background:var(--chip);padding:1px 4px;border-radius:4px;word-break:break-all}
.sent{font-size:13px;padding:1px 4px;border-radius:4px}.sent:target{background:#fff3b0;color:#111}.sec{font-weight:600;margin-top:6px;font-size:13px}
details.src{margin:6px 0 18px}a.evlink{font-size:12px;white-space:nowrap}h2{border-bottom:1px solid var(--line);padding-bottom:4px}
"""

_JS = """
document.addEventListener('click',function(ev){const a=ev.target.closest('a.evlink');if(!a)return;
const el=document.getElementById(a.getAttribute('href').slice(1));if(!el)return;
let d=el.closest('details');while(d){d.open=true;d=d.parentElement.closest('details');}});
async function fb(id,send){const t=document.getElementById('fb-'+id).value.trim();const m=document.getElementById('cmd-'+id);
if(!t){m.textContent='Write a comment first.';return;}
try{const r=await fetch('/api/comment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:id,text:t,send:send})});
const j=await r.json();m.textContent=(j.ok?'✓ ':'')+(j.message||j.error||'');if(j.ok)document.getElementById('fb-'+id).value='';}
catch(e){const c='sragent feedback --config CONFIG.yaml --target '+id+' --text "'+t.replace(/"/g,'\\"')+'"';
m.textContent='Open this report from the sragent UI (Report tab) to send comments directly. Or run: '+c;
navigator.clipboard&&navigator.clipboard.writeText(c).catch(()=>{});}}
"""


def _ev_txt(x: dict) -> str:
    """Evidence as text with locations (new format) or the legacy quote."""
    if x.get("spans"):
        return " | ".join(f"[{s['sid']}, {s['section']}] \"{s['text'][:300]}\"" for s in x["spans"])
    return f"\"{x.get('quote', '')}\"" if x.get("quote") else "(no location cited)"


def _ev_html(x: dict, rid: str | None) -> str:
    if x.get("spans"):
        out = []
        for s in x["spans"]:
            loc = f"{s['sid']} · {s['section']}"
            link = (f"<a class='evlink' href='#src-{_e(rid)}-{_e(s['sid'])}'>{_e(loc)}</a>" if rid
                    else f"<span class='b'>{_e(loc)}</span>")
            out.append(f"<div>{link} <span class='q'>“{_e(s['text'][:400])}”</span></div>")
        return "".join(out)
    if x.get("quote"):
        return f"<span class='q'>“{_e(x['quote'])}”</span>"
    return "<span class='q'>(no location cited)</span>"


def _source_html(ctx: Ctx, rid: str) -> str:
    from ..evidence import segment
    text, kind = ctx.store.text_of(rid)
    rows, sec = [], None
    for s in segment(text):
        if s["section"] != sec:
            sec = s["section"]
            rows.append(f"<div class='sec'>{_e(sec)}</div>")
        rows.append(f"<div class='sent' id='src-{_e(rid)}-{_e(s['sid'])}'><b>{_e(s['sid'])}</b> {_e(s['text'])}</div>")
    return (f"<details class='src' id='src-{_e(rid)}'><summary>Source text ({_e(kind)}, numbered sentences)</summary>"
            + "".join(rows) + "</details>")


def cited_populations(ctx: Ctx, cites: list[str]) -> str:
    out = []
    for c in cites:
        n = ctx.store.get(f"ext:{c}")
        if n and n["status"] == "active":
            out.append(f"[{c}] {n['data']['fields'].get('population', {}).get('value', 'NR')[:200]}")
    return "; ".join(out) or "(none)"


def _e(s) -> str:
    return html.escape(str(s if s is not None else ""))


def _badge(s) -> str:
    return f'<span class="b {_e(s)}">{_e(s)}</span>'


def _fbbox(nid: str) -> str:
    k = _e(nid)
    return (f'<details><summary>comment / ask the agent</summary><textarea id="fb-{k}" placeholder="Describe the error or '
            f'request"></textarea><button onclick="fb(\'{k}\',true)">Send to the agent</button> '
            f'<button onclick="fb(\'{k}\',false)">Save as a comment only</button> '
            f'<span class="q" id="cmd-{k}"></span></details>')


def _flags(n) -> str:
    return "".join(f'<div class="flag">⚑ {_e(f["text"])} ({_e(f["status"])})</div>' for f in n["flags"])


def report_html(ctx: Ctx) -> str:
    st = ctx.store
    p = st.get("protocol")["data"]
    pr = prisma(ctx)
    crit = _crit_lookup(ctx)
    H = [f"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
         f"<title>Evidence-linked review</title><style>{_CSS}</style><script>{_JS}</script></head><body>",
         f"<h1>{_e(review_title(p))}</h1><p><b>Question.</b> {_e(p.get('question'))}</p>",
         "<p class='q'>Research prototype. AI-generated; every item links to its evidence and must be verified by a human.</p>",
         "<h2>Selection (PRISMA)</h2><p>" + "; ".join(f"{_e(k)}: {_e(v)}" for k, v in pr.items()) + "</p>",
         "<h2>Synthesis</h2>"]
    for n in st.by_type("synthesis", active_only=True):
        d = n["data"]
        v = d.get("verification") or {}
        H.append(f"<div id='{_e(n['id'])}'><p><b>[{_e(d['id'])}]</b> {_e(d['text'])} "
                 + " ".join(f"<a href='#ext:{_e(c)}'>[{_e(c)}]</a>" for c in d["cites"])
                 + f" {_badge(v.get('support', 'unchecked'))} <span class='q'>scope: {_e(d.get('scope'))}; v{n['version']}</span></p>"
                 + f"<details><summary>populations of cited studies (check the scope)</summary><div class='q'>"
                 + _e(cited_populations(ctx, d["cites"])) + "</div></details>"
                 + _flags(n) + _fbbox(n["id"]) + "</div>")
    H.append("<h2>Included studies: extracted data with evidence</h2>")
    for rid in st.included_ids():
        n = st.get(f"ext:{rid}")
        if not n:
            continue
        rec = st.get(f"rec:{rid}")["data"]
        H.append(f"<h3 id='ext:{_e(rid)}'>[{_e(rid)}] {_e(rec.get('title'))}</h3>"
                 f"<p class='q'>{_e(rec.get('authors'))} {_e(rec.get('journal'))} {_e(rec.get('year'))} · source: "
                 f"{_e(n['data']['source_kind'])} · v{n['version']}</p>{_flags(n)}<table><tr><th>Item</th><th>Value</th><th>Evidence</th></tr>")
        for k, v in n["data"]["fields"].items():
            chk = v.get("check", {}).get("status", "")
            tm = "".join(f"<div>{_e(t['term'])} {_badge(t['status'])} {_e(t['ids'])}</div>" for t in v.get("terms", []))
            evh = "" if v["value"].strip().upper().startswith("NR") else _ev_html(v, rid)
            H.append(f"<tr><td>{_e(k)}</td><td>{_e(v['value'])}{tm}</td><td>{evh} "
                     f"{_badge(chk) if chk and chk != 'located' else ''}</td></tr>")
        H.append("</table>" + _fbbox(n["id"]))
        r = st.get(f"rob:{rid}")
        if r:
            H.append(f"<details id='rob:{_e(rid)}'><summary>Risk of bias draft: overall {_badge(r['data']['overall'])}</summary><table>"
                     "<tr><th>Domain</th><th>Judgment</th><th>Rationale</th><th>Evidence</th></tr>")
            for d in r["data"]["domains"]:
                H.append(f"<tr><td>{_e(d.get('domain'))}</td><td>{_badge(d.get('judgment'))}</td><td>{_e(d.get('rationale'))}</td>"
                         f"<td>{_ev_html(d, rid)}</td></tr>")
            H.append("</table>" + _flags(r) + _fbbox(r["id"]) + "</details>")
        H.append(_source_html(ctx, rid))
    H.append("<h2>All eligibility decisions</h2><table><tr><th>Record</th><th>Decision</th><th>Criteria</th></tr>")
    for n in st.by_type("screen"):
        rid = n["id"].split(":", 1)[1]
        d = n["data"]
        rec = st.get(f"rec:{rid}")["data"]
        crit_html = "".join(f"<div>{_e(a.get('id'))} {_badge(a.get('assessment'))} {_ev_html(a, None)}</div>"
                            for a in d.get("criteria", []))
        H.append(f"<tr id='screen:{_e(rid)}'><td>[{_e(rid)}] {_e(rec.get('title', '')[:120])}</td><td>{_badge(d['decision'])}"
                 f"<div class='q'>{_e(d['stage'])}; because {_e(', '.join(d.get('because', [])))}</div>{_flags(n)}</td>"
                 f"<td><details><summary>details</summary>{crit_html}</details>{_fbbox(n['id'])}</td></tr>")
    H.append("</table><h2>Criteria</h2><ul>" + "".join(f"<li>{_e(k)}: {_e(v)}</li>" for k, v in crit.items()) + "</ul>")
    changes = [c for c in st.changelog if c["op"] in ("update", "status")
               and (c["actor"] != "agent" or "feedback" in str(c.get("reason", "")))]
    if changes:
        H.append("<h2>Revision history (feedback-driven)</h2><ul>")
        for c in changes[-100:]:
            H.append(f"<li>{_e(c['node'])}: {_e(c['op'])} by {_e(c['actor'])} — {_e(str(c['reason'])[:200])}</li>")
        H.append("</ul>")
    H.append("</body></html>")
    return "\n".join(H)


def write_reports(ctx: Ctx):
    md = report_markdown(ctx)
    (ctx.run_dir / "report.md").write_text(md)
    (ctx.run_dir / "report_evidence.html").write_text(report_html(ctx))
    ctx.store.upsert("report", "report", {"prisma": prisma(ctx), "chars": len(md)},
                     depends_on=[n["id"] for n in ctx.store.by_type("synthesis", active_only=True)], reason="rendered")
    ctx.save()
    ctx.log(f"[report] wrote {ctx.run_dir / 'report.md'} and report_evidence.html")
